server:
  port: 8080
  servlet:
    context-path: /cc5c
spring:
  application:
    name: cc5c-manage
  # SqlServer 配置
  datasource:
    url: jdbc:mysql://cdb-21vrmzey.bj.tencentcdb.com:10141/cc5c2?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zlloveljp1314
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
  #文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 2048KB
      max-request-size: 10240KB
      file-size-threshold: 0
  mail:
    host: smtp.163.com
    username: ceshifs123@163.com
    password: shebeitishi1
    protocol: smtp
    port: 465
    properties:
      mail:
        debug: true
        smtp:
          socketFactory.class: javax.net.ssl.SSLSocketFactory
          auth: true
          timeout: 25000
          enable:
          socketFactory.fallback: false
          socketFactory.port: 465
    default-encoding: UTF-8

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.cc5c.entity

# pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql